# version: 2.1

# jobs:
#   test:
#     docker:
#       - image: cimg/python:3.10
#     parallelism: 4   #  4 containers will run in parallel
#     steps:
#       - checkout
#       - run:
#           name: Install dependencies
#           command: pip install -r requirements.txt
#       - run:
#           name: Run tests in parallel
#           command: |
#             circleci tests split --split-by=timings test-files.txt | xargs pytest -v

# workflows:
#   version: 2
#   test-workflow:
#     jobs:
#       - test

version: 2.1

jobs:
  run-small:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: "Run on small (1 CPU, 2GB RAM)"
          command: |
            echo "Running on SMALL resource class"
            sudo apt-get update && sudo apt-get install -y stress
            stress --cpu 1 --timeout 10s

  run-medium:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - run:
          name: "Run on medium (2 CPUs, 4GB RAM)"
          command: |
            echo "Running on MEDIUM resource class"
            sudo apt-get update && sudo apt-get install -y stress
            stress --cpu 2 --timeout 10s

workflows:
  demo:
    jobs:
      - run-small
      - run-medium
